#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 23 14:44:20 2020

@author: jguterl
"""
import omfit
omfit.loadModule('OMFITprofiles')
OMFIT['OMFITprofiles'].experiment(shot=,times=[])
OMFIT['OMFITprofiles']['SCRIPTS']['extract_profiles'].run()