      subroutine CopyAux
      use OmpCopybbb
      implicit none
      call OmpCopyPointerne
      call OmpCopyPointernit
      call OmpCopyPointernm
      call OmpCopyPointernz2
      call OmpCopyPointerni
      call OmpCopyPointerng
      call OmpCopyPointerlng
      call OmpCopyPointerte
      call OmpCopyPointertg
      call OmpCopyPointerti
      call OmpCopyPointerphi
      call OmpCopyPointerup
      call OmpCopyPointerpr
      call OmpCopyPointerzeff
      call OmpCopyPointerpri
      call OmpCopyPointerpre
      call OmpCopyPointerznot
      call OmpCopyPointertg
      call OmpCopyPointerpg
      call OmpCopyPointergprx
      call OmpCopyPointerney0
      call OmpCopyPointerney1
      call OmpCopyPointernity0
      call OmpCopyPointernity1
      call OmpCopyPointergpry
      call OmpCopyPointergpix
      call OmpCopyPointerniy0
      call OmpCopyPointerniy1
      call OmpCopyPointerniy0s
      call OmpCopyPointerniy1s
      call OmpCopyPointerpriy0
      call OmpCopyPointerpriy1
      call OmpCopyPointergpiy
      call OmpCopyPointertey0
      call OmpCopyPointertey1
      call OmpCopyPointertiy0
      call OmpCopyPointertiy1
      call OmpCopyPointerphiy0
      call OmpCopyPointerphiy1
      call OmpCopyPointertiy0s
      call OmpCopyPointertiy1s
      call OmpCopyPointerphiy0s
      call OmpCopyPointerphiy1s
      call OmpCopyPointerngy0
      call OmpCopyPointerngy1
      call OmpCopyPointertgy0
      call OmpCopyPointertgy1
      call OmpCopyPointerpgy0
      call OmpCopyPointerpgy1
      call OmpCopyPointergpex
      call OmpCopyPointergtex
      call OmpCopyPointergtix
      call OmpCopyPointerex
      call OmpCopyPointergpey
      call OmpCopyPointergtey
      call OmpCopyPointergtiy
      call OmpCopyPointerey
      call OmpCopyPointerphiv
      call OmpCopyPointertiv
      call OmpCopyPointertev
      call OmpCopyPointerprev
      call OmpCopyPointerprtv
      call OmpCopyPointerpriv
      end subroutine CopyAux
